title: mnz.pt # name of the site
author: Paulo Moniz # name of site's author
email: paulo@mnz.pt # email of site's author
url: https://mnz.pt/ # root address of the site
description: > # description of the site (multiple lines allowed)
  um sítio simples de uma singela pessoa

permalink: :categories/:slug

favicon: "./logo.png" # relative path to site's favicon
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: "mnz.pt" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page


sass:
  style: :compressed

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
